In [3]:
import numpy as np
from numpy import random
random.uniform(0,1,6)


array([0.24131253, 0.69818933, 0.37085934, 0.14529236, 0.38800055,
       0.76729256])

In [4]:
rand(1,2,3)

NameError: name 'rand' is not defined

In [5]:
np.rand(1,2,3)

AttributeError: module 'numpy' has no attribute 'rand'

In [10]:
random.rand(5,2,3,4)

array([[[[0.39154164, 0.45252315, 0.27986392, 0.14230356],
         [0.06158477, 0.87259642, 0.81767699, 0.45124253],
         [0.47899236, 0.77425374, 0.59386442, 0.99868775]],

        [[0.88756906, 0.66155222, 0.57066348, 0.93169131],
         [0.00481201, 0.74078394, 0.48026481, 0.71634247],
         [0.84429791, 0.30154198, 0.84799109, 0.49182615]]],


       [[[0.64393622, 0.44379077, 0.24355699, 0.92910817],
         [0.01702763, 0.03082504, 0.37178618, 0.67026102],
         [0.1146561 , 0.01495943, 0.03230991, 0.35963387]],

        [[0.49501558, 0.54755379, 0.24313855, 0.14761657],
         [0.21034515, 0.98357625, 0.59354142, 0.3773259 ],
         [0.26846674, 0.69756869, 0.14343864, 0.75335645]]],


       [[[0.15898344, 0.98669759, 0.33034474, 0.50585164],
         [0.30601578, 0.86950864, 0.60087975, 0.80382647],
         [0.00952908, 0.68750892, 0.99953518, 0.27751881]],

        [[0.45423266, 0.3412072 , 0.55938596, 0.16487099],
         [0.82688159, 0.18902157, 0.166713

In [11]:
random.rand(5,2,3)

array([[[0.59333036, 0.51803318, 0.83823406],
        [0.32882992, 0.15315086, 0.22821206]],

       [[0.20274184, 0.96390826, 0.08256576],
        [0.24667056, 0.6832755 , 0.43703725]],

       [[0.91547476, 0.89836194, 0.2850398 ],
        [0.28337339, 0.35233494, 0.33442281]],

       [[0.10096709, 0.63475388, 0.11815467],
        [0.40705541, 0.70313969, 0.9335614 ]],

       [[0.39262331, 0.97173928, 0.14150252],
        [0.96837131, 0.84028648, 0.34886554]]])

In [1]:
np.array([1,1,1],[1,1,1],[1,1,1])

NameError: name 'np' is not defined

In [3]:
numpy.array([1,1,1],[1,1,1],[1,1,1])

NameError: name 'numpy' is not defined

In [6]:
import numpy
a=numpy.array(([1,1,1],[1,1,1],[1,1,1]))
sum_array=sum(a)
sum_array/len(a)

array([1., 1., 1.])

In [7]:
list=[(1,"a"),(2,"b")]
max(list,key=lambda tuple:tuple[1])

(2, 'b')